public/question.css

The lines in a `<pre>` code block may slightly overlap. Lower parts of a line can thus be obcured by the next one. This PR removes the background of `<code>` when it's inside a `<pre>` which already has the same  background color set.
Before (missing underscores and lower parts of lowercase Ys):
After:

Remove inline CSS backgrounds in a code block

---

public/question.css

This PR adds more style to the notice box. It looks odd currently.
Before PR:
After PR:
Example taken from: https://stackoverflow.com/questions/60174/how-can-i-prevent-sql-injection-in-php?rq=1

Fix notice box styles

---

templates/question.html

This patch adds anonymousoverflow to the title of questions, making tracking anonymousoverflow through things like activitywatch easier..

Add AnonymousOverflow to question title

---

src/middleware/options.go
src/routes/options.go

Fixes a bug where if the disable_images cookie was not present, the theme cookie would not be parsed.
Addresses #31

Fix options cookie parsing bug

---

main.go

This is a follow up to #50
Stackoverflow also supports links such as `https://stackoverflow.com/q/77188146`, and redirects them to `/questions/{id}`. SearXNG uses this for example (e.g. https://searx.be/search?q=!stackoverflow%20test), hence this PR is needed to properly redirect these URLs to AnonymousOverflow.

fix: redirect shortened 'a' URLs

---

src/routes/question.go

Addresses #85 by deriving currentUrl with actual path.

Fix theme button redirecting to incorrect URL

---

go.mod
go.sum
src/routes/question.go
src/utils/comments.go
src/utils/links.go
src/utils/links_test.go
src/utils/process.go

* Addresses #85 by replacing stackoverflow and stackexchange links within posts, answers and comments with instance ones.

Replace StackOverflow Links

---

src/routes/question.go

* Prevents HTML from rendering in comments during syntax highlighting

fix: keep HTML escaped

---

src/routes/home.go
src/routes/home_test.go
src/routes/question.go

Implement external exchanges

---

config/version.go
main.go

This pull request fixes the current behavior where shortened URLs such as `https://stackoverflow.com/a/48490543/446106` return a 404 page.

Add redirect endpoint for shortened urls with an answer id

---

public/globals.css
public/home.css
public/question.css

This mainly fixes code not visible in light theme:
also use hex code instead of `rgb` code for all.

fix code not visible in light theme

---

public/globals.css
public/home.css
public/question.css
templates/question.html

Referencing GH-45: 50% is really narrow on smaller screen sizes, the maximum width should instead be calculated from the font size.
Some rules are removed to correct the bounding box size
in browser inspector and fix the overflow on the x-axis.
The now-unused div.parent is removed; please hide whitespace changes when view the diff for better clarity.

Set maximum width to 40rem across screen sizes

---

templates/home.html
templates/question.html

fix: remove alt from homepage logo, add "logo" alt to question header

---

instances.json

Related to #136
Update the server domain and operator in `instances.json` to reflect the new domain and operator.
* Change the `url` field from `https://ao.ftw.lol` to `https://ao.rootdo.com`.
* Change the `operators` field from `https://ftw.lol` to `https://rootdo.com`.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/httpjamesm/AnonymousOverflow/issues/136?shareId=cc4cf1d0-7aa5-4fe4-bf79-9ef0b0640e2a).

Instance domain change

---

public/globals.css
src/routes/home.go
src/routes/options.go
src/routes/question.go
src/utils/theme.go
templates/home.html
templates/question.html

Related to #140
Add support for theme environment variable and update theme switching logic.
* **CSS Changes**: Modify `public/globals.css` to handle the `data-theme` attribute for light and dark themes while keeping the `prefers-color-scheme` media query.
* **Home Route**: Update `src/routes/home.go` to read the `THEME` environment variable and pass it to the template.
* **Question Route**: Update `src/routes/question.go` to read the `THEME` environment variable and pass it to the template.
* **Home Template**: Modify `templates/home.html` to add a `data-theme` attribute to the `html` tag and set its value based on the `THEME` environment variable.
* **Question Template**: Modify `templates/question.html` to add a `data-theme` attribute to the `html` tag and set its value based on the …

Add theme support using environment variable

---

main.go
src/routes/version.go

Related to #137
Add an endpoint to return the instance version as a string.
* **New file `src/routes/version.go`**:
- Create a new file to define the version endpoint.
- Import necessary packages.
- Define a function `GetVersion` that returns the version as a string.
* **Modify `main.go`**:
- Import the new version route.
- Add a new route to the router for the version endpoint.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/httpjamesm/AnonymousOverflow/issues/137?shareId=7593fcc1-b443-4ec7-a9b2-7bd3aab16283).

Add version endpoint

---

README.md

Related to #108
Update the link in the `README.md` to point to the new URL for the Proxy_Redirect user.js script.
* Change the link in the `README.md` from https://openuserjs.org/scripts/sjehuda/FREEdirector to https://openuserjs.org/scripts/sjehuda/Proxy_Redirect.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/httpjamesm/AnonymousOverflow/issues/108?shareId=09835730-90ce-48aa-a4a6-82ee6dff3874).

Update README link to Proxy_Redirect

---

instances.json

Related to #142
Update the operator link and name for the instance `https://soflow.nerdvpn.de` in `instances.json`.
* Change the operator link from `https://github.com/Sommerwiesel` to `https://nerdvpn.de`.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/httpjamesm/AnonymousOverflow/issues/142?shareId=c6e8f03b-0968-49c5-896e-ca0380b12795).

Instance operator change - soflow.nerdvpn.de

---

instances.json

I previously ran an instance at anonoverflow.nirn.quest. I have renamed the domain to anonoverflow.hyperreal.coffee.

anonoverflow.nirn.quest --> anonoverflow.hyperreal.coffee

---

public/globals.css

This should fix an issue with mobile layout when the link is too long and it changes the page width.
For example on this page: https://ao.bloat.cat/questions/7244321/how-do-i-update-or-sync-a-forked-repository-on-github

Add "word-wrap: break-word" for links
